### PR TITLE
requirements: add proxybroker to the req__List

### PR DESCRIPTION
**Pull request by karthik558**
Fixes missing module named proxybroker on windows 

Signed-off-by : K A R T H I K <karthik.lal558@gmail.com>

### CODE REVIEW

**Comment by Crevils** [comment]
I am not using proxybroker

**Comment by karthik558** [comment]
Sadly windows showed error , without installing proxybroker it will not run the script

**Comment by karthik558** [comment]
image


What is this ?

**Comment by Crevils** [comment]
Ohh sad wait lemme fix that

**Pull request closed without merging**
